const expresse = require("express")
const app = expresse()
app.set("view engine", "ejs")
app.listen(3000, function(){console.log("http://localhost:"+3000)})
app.get("/", function(req, res){res.send("Hallo word")})